### ISSUE TITLE
Filters out errors in `path.join`

### ISSUE THREAD

**Issue by vjpr** [AndreasMadsen/clarify#7]
Before

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at join (path.js:1211:7)
    at LinkedPackage._callee4$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:99:36)
...
```

After

```
TypeError: Path must be a string. Received undefined
    at LinkedPackage._callee4$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:99:36)
    at LinkedPackage.getNpmLinkedVersion (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:100:2
...
```

---

We lose a bit of useful information here.

The full stack trace looks like (using longjohn):

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at join (path.js:1211:7)
    at LinkedPackage._callee4$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:99:36)
    at LinkedPackage.getNpmLinkedVersion (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:100:25)
    at VersionChecker._callee8$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:155:33)
---------------------------------------------
    at Object.<anonymous> (/Users/Vaughan/dev-live/shipmate/src/index.js:13:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Vaughan/dev-live/shipmate/src/cli/publish.js:1:1)
```

I am not interested in the `module.js` require-related stack trace.

Perhaps a better filter would be to keep internal frames the lead to the error up until the first call to a non-internal call.

E.g. the above trace would become:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at join (path.js:1211:7)
    at LinkedPackage._callee4$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:99:36)
    at LinkedPackage.getNpmLinkedVersion (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:100:25)
    at VersionChecker._callee8$ (/Users/Vaughan/dev-live/shipmate/src/plugins/linked-modules/index.js:155:33)
---------------------------------------------
    at Object.<anonymous> (/Users/Vaughan/dev-live/shipmate/src/index.js:13:9)
    { removed }
    at Object.<anonymous> (/Users/Vaughan/dev-live/shipmate/src/cli/publish.js:1:1)
```

**Comment by vjpr** [comment]
It appears the `longjohn` triggers a call to `chain.filter.attach` for each async stack trace.

**Comment by vjpr** [comment]
I threw this together which works...

```
function filterInternals() {
  const chain = require('stack-chain')
  const sep = require('path').sep
  const _ = require('lodash')
  chain.filter.attach(function(error, frames) {
    function isInternal(callSite) {
      var name = callSite && callSite.getFileName()
      return (name && name.indexOf(sep) === -1)
    }
    const out = _(frames)
      .takeWhile(isInternal)
      .concat(_(frames)
        .dropWhile(isInternal)
        .reject(isInternal)
        .value())
      .value()
    return out
  })
}
```

**Comment by AndreasMadsen** [comment]
I think the idea is good. Unfortunately this will not work if a long stack trace tool joins by string instead of CallSite objects, which some do to conserve memory.

**Comment by AndreasMadsen** [comment]
I think this is outside the scope of clarify, it is simply not possible to implement and remain compatible to the same degree as `clarify` allows now.

If anything `trace` should add information about the _async depth_ such the necessary information to produce such a stack exists. One could then implement a formatter that used that extra information, but you are using `longjohn` which is outside my control.
